export function captureException(error: any) {
  console.warn('Expected error - ', error);
}
